
# Netlify configuration file

# This redirect rule tells Netlify to serve the index.html for all routes
# This is crucial for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# Cache control for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
